spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        ## bulk insert ?? ##
        # ?? ??
        order_inserts: true
        order_updates: true
        # ?? ?? ??
        jdbc.batch_size: 100
        query:
          fail_on_pagination_over_collection_fetch: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/soccer?rewriteBatchedStatements=true
    username: root
    password: 661899
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing.include-parameter-values: true

springdoc:
  paths-to-match: /**
  use-fqn: true